type: plugin
files:
    src:
        - '**'
        - '!node_modules/**'
        - '!vendor/**'
        - '!tests/**'
        - '!test/**'
        - '!build/**'
        - '!tmp/**'
        - '!README.md'
    main: wp-dummy-plugin.php
    assets:
        - assets/wporg/*.png
        - assets/wporg/*.svg
gh:
    repo: GedexTestOrg/wp-dummy-plugin
    username: GedexTestOrg
wporg:
    slug: wp-dummy-plugin
    username: akeda
    buildPath: build
